//! Curated engine-specific keyword and builtin-function tables.
//!
//! Lists are static and compile-time. They are the "engine-specific
//! function/keyword tables" called out in the Phase D plan. Kept
//! deliberately small — the common cases a typing user actually reaches
//! for, not exhaustive references. Extend as friction shows up.

use sift_protocol::Engine;

/// Statement-lead keywords (SELECT, INSERT, ...). Both engines share
/// this list; it's what shows up first when the cursor is at
/// `CompletionContext::Statement`.
pub const STATEMENT_LEADS: &[&str] = &[
    "SELECT",
    "INSERT",
    "UPDATE",
    "DELETE",
    "WITH",
    "CREATE",
    "ALTER",
    "DROP",
    "TRUNCATE",
    "EXPLAIN",
    "BEGIN",
    "COMMIT",
    "ROLLBACK",
    "SAVEPOINT",
];

/// General SQL keywords useful mid-statement. Bounded list — the point
/// isn't to enumerate the grammar, only what users type.
pub const COMMON_KEYWORDS: &[&str] = &[
    "AS",
    "AND",
    "OR",
    "NOT",
    "NULL",
    "IS",
    "IN",
    "LIKE",
    "BETWEEN",
    "EXISTS",
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "GROUP",
    "BY",
    "HAVING",
    "ORDER",
    "ASC",
    "DESC",
    "LIMIT",
    "OFFSET",
    "UNION",
    "INTERSECT",
    "EXCEPT",
    "ALL",
    "DISTINCT",
    "FROM",
    "WHERE",
    "JOIN",
    "INNER",
    "LEFT",
    "RIGHT",
    "FULL",
    "OUTER",
    "CROSS",
    "ON",
    "USING",
    "INTO",
    "VALUES",
    "SET",
    "RETURNING",
];

pub const PG_KEYWORDS: &[&str] = &[
    "LATERAL",
    "WINDOW",
    "OVER",
    "PARTITION",
    "FETCH",
    "FIRST",
    "ROWS",
    "ONLY",
    "MATERIALIZED",
    "RECURSIVE",
    "TEMP",
    "TEMPORARY",
    "UNLOGGED",
    "CONFLICT",
    "DO",
    "NOTHING",
    "EXCLUDED",
];

pub const MSSQL_KEYWORDS: &[&str] = &[
    "TOP",
    "OUTPUT",
    "MERGE",
    "PIVOT",
    "UNPIVOT",
    "APPLY",
    "OUTER",
    "GO",
    "IDENTITY",
    "NVARCHAR",
    "NOLOCK",
    "READPAST",
    "WITH",
    "TABLESAMPLE",
];

pub const PG_FUNCTIONS: &[&str] = &[
    "count",
    "sum",
    "avg",
    "min",
    "max",
    "coalesce",
    "nullif",
    "greatest",
    "least",
    "now",
    "current_timestamp",
    "current_date",
    "current_time",
    "current_user",
    "session_user",
    "extract",
    "date_trunc",
    "date_part",
    "to_char",
    "to_date",
    "to_timestamp",
    "length",
    "char_length",
    "upper",
    "lower",
    "trim",
    "ltrim",
    "rtrim",
    "concat",
    "concat_ws",
    "substring",
    "position",
    "replace",
    "split_part",
    "regexp_match",
    "regexp_replace",
    "regexp_split_to_array",
    "regexp_split_to_table",
    "array_agg",
    "string_agg",
    "json_agg",
    "jsonb_agg",
    "jsonb_build_object",
    "jsonb_path_query",
    "row_number",
    "rank",
    "dense_rank",
    "lag",
    "lead",
    "first_value",
    "last_value",
    "generate_series",
    "unnest",
    "array_length",
    "cardinality",
];

pub const MSSQL_FUNCTIONS: &[&str] = &[
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "ISNULL",
    "COALESCE",
    "NULLIF",
    "IIF",
    "CHOOSE",
    "GETDATE",
    "SYSDATETIME",
    "SYSUTCDATETIME",
    "CURRENT_TIMESTAMP",
    "DATEADD",
    "DATEDIFF",
    "DATEPART",
    "DATENAME",
    "YEAR",
    "MONTH",
    "DAY",
    "FORMAT",
    "CONVERT",
    "CAST",
    "TRY_CAST",
    "TRY_CONVERT",
    "LEN",
    "DATALENGTH",
    "UPPER",
    "LOWER",
    "LTRIM",
    "RTRIM",
    "TRIM",
    "CONCAT",
    "CONCAT_WS",
    "SUBSTRING",
    "CHARINDEX",
    "REPLACE",
    "STUFF",
    "STRING_AGG",
    "STRING_SPLIT",
    "ROW_NUMBER",
    "RANK",
    "DENSE_RANK",
    "NTILE",
    "LAG",
    "LEAD",
    "FIRST_VALUE",
    "LAST_VALUE",
    "OBJECT_ID",
    "OBJECT_NAME",
    "OBJECT_DEFINITION",
    "SCOPE_IDENTITY",
    "NEWID",
    "HASHBYTES",
];

pub fn keywords_for(engine: Engine) -> Vec<&'static str> {
    let mut out: Vec<&'static str> = Vec::new();
    out.extend(STATEMENT_LEADS);
    out.extend(COMMON_KEYWORDS);
    match engine {
        Engine::Postgres => out.extend(PG_KEYWORDS),
        Engine::SqlServer => out.extend(MSSQL_KEYWORDS),
    }
    out
}

pub fn functions_for(engine: Engine) -> &'static [&'static str] {
    match engine {
        Engine::Postgres => PG_FUNCTIONS,
        Engine::SqlServer => MSSQL_FUNCTIONS,
    }
}
