//! DDL → object → DDL round-trip test against a real Postgres.
//!
//! For each fixture object (table, view, materialized view, procedure)
//! we:
//!   1. Create it in a source schema.
//!   2. Ask `sift_server::ddl::generate_ddl` for the DDL text.
//!   3. Execute the DDL against a fresh destination schema.
//!   4. Re-introspect both schemas with `Driver::schema(Deep)`.
//!   5. Assert the introspection results are equivalent (columns,
//!      constraints, indexes — ignoring names when they'd naturally
//!      differ across schemas).
//!
//! This test is gated behind the `live-pg` feature so `cargo test` in
//! a bare devshell stays green. Bring up a throwaway PG the same way
//! the `sift-driver-postgres::live_pg` test suite does:
//!
//! ```text
//! SIFT_PG_HOST=/tmp/sift-pg-socket SIFT_PG_PORT=5433 \
//!   cargo test -p sift-server --features live-pg --test ddl_round_trip -- --nocapture
//! ```

#![cfg(feature = "live-pg")]

use std::sync::atomic::{AtomicU64, Ordering};

use sift_driver_api::{ConnHandle, Driver};
use sift_driver_postgres::PgDriver;
use sift_protocol::{
    ConnectionSpec, ConstraintInfo, ExecuteRequest, IndexInfo, ObjectInfo, ObjectKind, ObjectPath,
    Page, SchemaDepth, SchemaFilter, SchemaScope, SslMode,
};
use sift_server::ddl::generate_ddl;

const DEFAULT_PG_HOST: &str = "/tmp/opencode/sift-pg-socket";
const DEFAULT_PG_PORT: u16 = 5433;
const DEFAULT_PG_USER: &str = "sift";
const DEFAULT_PG_DB: &str = "sifttest";

static SCHEMA_COUNTER: AtomicU64 = AtomicU64::new(0);

fn unique_schema(suffix: &str) -> String {
    // PG identifier limit is 63 bytes; keep the schema short and unique
    // per test invocation via a nanosecond stamp + counter.
    let n = SCHEMA_COUNTER.fetch_add(1, Ordering::Relaxed);
    let stamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("rt_{suffix}_{n}_{stamp:x}")
}

fn spec() -> ConnectionSpec {
    ConnectionSpec {
        host: std::env::var("SIFT_PG_HOST").unwrap_or_else(|_| DEFAULT_PG_HOST.to_string()),
        port: Some(
            std::env::var("SIFT_PG_PORT")
                .ok()
                .and_then(|p| p.parse().ok())
                .unwrap_or(DEFAULT_PG_PORT),
        ),
        database: Some(std::env::var("SIFT_PG_DB").unwrap_or_else(|_| DEFAULT_PG_DB.to_string())),
        user: std::env::var("SIFT_PG_USER").unwrap_or_else(|_| DEFAULT_PG_USER.to_string()),
        password: std::env::var("SIFT_PG_PASSWORD").ok(),
        ssl_mode: Some(SslMode::Disable),
        engine_specific: None,
    }
}

async fn exec(driver: &PgDriver, conn: &ConnHandle, sql: impl Into<String>) {
    let sql = sql.into();
    let stream = driver
        .execute(conn.clone(), ExecuteRequest::new(sql.clone()))
        .await
        .unwrap_or_else(|e| panic!("execute call failed ({e}) for SQL:\n{sql}"));
    let mut rx = stream.rows;
    while let Some(page) = rx.recv().await {
        if let Page::Error { error } = page {
            panic!("execute produced Page::Error ({error}) for SQL:\n{sql}");
        }
    }
}

async fn exec_many(driver: &PgDriver, conn: &ConnHandle, sqls: &[String]) {
    for s in sqls {
        exec(driver, conn, s.as_str()).await;
    }
}

/// Deep-introspect one object in a schema.
async fn introspect(
    driver: &PgDriver,
    conn: &ConnHandle,
    schema: &str,
    name: &str,
    kind: ObjectKind,
) -> ObjectInfo {
    let scope = SchemaScope {
        depth: SchemaDepth::Deep {
            object: ObjectPath {
                catalog: None,
                schema: Some(schema.into()),
                name: name.into(),
                kind: Some(kind),
                routine_args: None,
            },
        },
        filter: None,
    };
    let snap = driver
        .schema(conn.clone(), scope)
        .await
        .expect("deep schema succeeds");
    snap.trees
        .into_iter()
        .flat_map(|c| c.schemas.into_iter())
        .flat_map(|s| s.objects.into_iter())
        .find(|o| o.name == name)
        .unwrap_or_else(|| panic!("object {schema}.{name} not present in deep snapshot"))
}

/// Assert two `ObjectInfo`s describe the same shape. We compare structural
/// properties, not identity fields that inherently differ across schemas
/// (constraint names, index names auto-generated by PG).
fn assert_object_equivalent(src: &ObjectInfo, dst: &ObjectInfo, ctx: &str) {
    assert_eq!(src.kind, dst.kind, "{ctx}: kind differs");
    assert_eq!(
        src.columns.len(),
        dst.columns.len(),
        "{ctx}: column count differs: src={:?} dst={:?}",
        src.columns.iter().map(|c| &c.name).collect::<Vec<_>>(),
        dst.columns.iter().map(|c| &c.name).collect::<Vec<_>>()
    );
    for (a, b) in src.columns.iter().zip(&dst.columns) {
        assert_eq!(a.name, b.name, "{ctx}: column name differs");
        assert_eq!(a.nullable, b.nullable, "{ctx}: {} nullability", a.name);
        // Type equality goes via TypeRef's PartialEq — round-tripped
        // types should land back on the same primitive/native pair.
        assert_eq!(a.type_ref, b.type_ref, "{ctx}: {} type", a.name);
    }
    assert_constraints_equivalent(&src.constraints, &dst.constraints, ctx);
    assert_indexes_equivalent(&src.indexes, &dst.indexes, ctx);
}

fn assert_constraints_equivalent(src: &[ConstraintInfo], dst: &[ConstraintInfo], ctx: &str) {
    // Group by kind + column set — the constraint *name* is
    // auto-generated by PG and won't match across schemas.
    let key = |c: &ConstraintInfo| {
        let mut cols = c.columns.clone();
        cols.sort();
        (c.kind, cols)
    };
    let mut src_keys: Vec<_> = src.iter().map(key).collect();
    let mut dst_keys: Vec<_> = dst.iter().map(key).collect();
    src_keys.sort_by(|a, b| format!("{a:?}").cmp(&format!("{b:?}")));
    dst_keys.sort_by(|a, b| format!("{a:?}").cmp(&format!("{b:?}")));
    assert_eq!(
        src_keys, dst_keys,
        "{ctx}: constraint set differs (excluding names)"
    );
}

fn assert_indexes_equivalent(src: &[IndexInfo], dst: &[IndexInfo], ctx: &str) {
    let key = |i: &IndexInfo| {
        let mut cols = i.columns.clone();
        cols.sort();
        (i.unique, i.primary_key, cols, i.partial_predicate.clone())
    };
    let mut src_keys: Vec<_> = src.iter().map(key).collect();
    let mut dst_keys: Vec<_> = dst.iter().map(key).collect();
    src_keys.sort_by(|a, b| format!("{a:?}").cmp(&format!("{b:?}")));
    dst_keys.sort_by(|a, b| format!("{a:?}").cmp(&format!("{b:?}")));
    assert_eq!(
        src_keys, dst_keys,
        "{ctx}: index set differs (excluding names)"
    );
}

/// Take a DDL string generated for `src_schema` and rewrite bare schema
/// references so it applies cleanly against `dst_schema`.
///
/// The generator uses `"schema"."name"` throughout; textual replace of
/// the quoted schema token is safe because identifier quoting isolates
/// it from any other occurrence.
fn retarget_schema(ddl: &str, src_schema: &str, dst_schema: &str) -> String {
    ddl.replace(&format!("\"{src_schema}\"."), &format!("\"{dst_schema}\"."))
}

#[tokio::test]
async fn round_trip_table_with_pk_fk_check_unique_index() {
    let driver = PgDriver::new();
    let conn = driver.open(&spec()).await.expect("open");
    let src = unique_schema("src_tbl");
    let dst = unique_schema("dst_tbl");

    exec_many(
        &driver,
        &conn,
        &[
            format!("CREATE SCHEMA \"{src}\""),
            format!("CREATE SCHEMA \"{dst}\""),
            format!(
                "CREATE TABLE \"{src}\".\"parent\" (
                    id integer PRIMARY KEY,
                    name text NOT NULL
                )"
            ),
            format!(
                "CREATE TABLE \"{src}\".\"child\" (
                    id integer PRIMARY KEY,
                    parent_id integer NOT NULL REFERENCES \"{src}\".\"parent\"(id),
                    email text NOT NULL,
                    age integer,
                    CONSTRAINT child_email_unique UNIQUE (email),
                    CONSTRAINT child_age_nonneg CHECK (age IS NULL OR age >= 0)
                )"
            ),
            format!(
                "CREATE INDEX child_email_idx
                    ON \"{src}\".\"child\" (email)
                    WHERE email IS NOT NULL"
            ),
        ],
    )
    .await;

    // The child table references parent, so parent's DDL must be
    // applied to dst first for the FK to resolve on re-create.
    for name in ["parent", "child"] {
        let path = ObjectPath {
            catalog: None,
            schema: Some(src.clone()),
            name: name.into(),
            kind: Some(ObjectKind::Table),
            routine_args: None,
        };
        let generated = generate_ddl(&driver, conn.clone(), path)
            .await
            .expect("generate table DDL")
            .ddl;
        let retargeted = retarget_schema(&generated, &src, &dst);
        // The generator emits multiple statements separated by `;\n`
        // (table + one or more `CREATE INDEX`). Execute each.
        for stmt in retargeted.split(";\n").filter(|s| !s.trim().is_empty()) {
            exec(&driver, &conn, stmt.trim_end_matches(';')).await;
        }
    }

    for name in ["parent", "child"] {
        let src_info = introspect(&driver, &conn, &src, name, ObjectKind::Table).await;
        let dst_info = introspect(&driver, &conn, &dst, name, ObjectKind::Table).await;
        assert_object_equivalent(&src_info, &dst_info, name);
    }

    driver.close(conn).await.unwrap();
}

#[tokio::test]
async fn round_trip_view() {
    let driver = PgDriver::new();
    let conn = driver.open(&spec()).await.expect("open");
    let src = unique_schema("src_view");
    let dst = unique_schema("dst_view");

    exec_many(
        &driver,
        &conn,
        &[
            format!("CREATE SCHEMA \"{src}\""),
            format!("CREATE SCHEMA \"{dst}\""),
            format!(
                "CREATE TABLE \"{src}\".\"items\" (id integer PRIMARY KEY, price numeric NOT NULL)"
            ),
            format!(
                "CREATE VIEW \"{src}\".\"expensive_items\" AS
                    SELECT id, price FROM \"{src}\".\"items\" WHERE price > 100"
            ),
            // Destination has the same underlying table so the view's
            // SELECT resolves after we retarget it.
            format!(
                "CREATE TABLE \"{dst}\".\"items\" (id integer PRIMARY KEY, price numeric NOT NULL)"
            ),
        ],
    )
    .await;

    let path = ObjectPath {
        catalog: None,
        schema: Some(src.clone()),
        name: "expensive_items".into(),
        kind: Some(ObjectKind::View),
        routine_args: None,
    };
    let ddl = generate_ddl(&driver, conn.clone(), path)
        .await
        .expect("generate view DDL")
        .ddl;
    exec(&driver, &conn, retarget_schema(&ddl, &src, &dst)).await;

    let src_info = introspect(&driver, &conn, &src, "expensive_items", ObjectKind::View).await;
    let dst_info = introspect(&driver, &conn, &dst, "expensive_items", ObjectKind::View).await;
    assert_object_equivalent(&src_info, &dst_info, "expensive_items");
    driver.close(conn).await.unwrap();
}

#[tokio::test]
async fn round_trip_materialized_view() {
    let driver = PgDriver::new();
    let conn = driver.open(&spec()).await.expect("open");
    let src = unique_schema("src_mv");
    let dst = unique_schema("dst_mv");

    exec_many(
        &driver,
        &conn,
        &[
            format!("CREATE SCHEMA \"{src}\""),
            format!("CREATE SCHEMA \"{dst}\""),
            format!(
                "CREATE TABLE \"{src}\".\"events\" (id integer PRIMARY KEY, kind text NOT NULL)"
            ),
            format!(
                "CREATE MATERIALIZED VIEW \"{src}\".\"event_counts\" AS
                    SELECT kind, COUNT(*) AS n FROM \"{src}\".\"events\" GROUP BY kind"
            ),
            format!(
                "CREATE TABLE \"{dst}\".\"events\" (id integer PRIMARY KEY, kind text NOT NULL)"
            ),
        ],
    )
    .await;

    let path = ObjectPath {
        catalog: None,
        schema: Some(src.clone()),
        name: "event_counts".into(),
        kind: Some(ObjectKind::MaterializedView),
        routine_args: None,
    };
    let ddl = generate_ddl(&driver, conn.clone(), path)
        .await
        .expect("generate MV DDL")
        .ddl;
    assert!(
        ddl.contains("CREATE MATERIALIZED VIEW"),
        "MV DDL missing prefix: {ddl}"
    );
    exec(&driver, &conn, retarget_schema(&ddl, &src, &dst)).await;

    let src_info = introspect(
        &driver,
        &conn,
        &src,
        "event_counts",
        ObjectKind::MaterializedView,
    )
    .await;
    let dst_info = introspect(
        &driver,
        &conn,
        &dst,
        "event_counts",
        ObjectKind::MaterializedView,
    )
    .await;
    assert_object_equivalent(&src_info, &dst_info, "event_counts");
    driver.close(conn).await.unwrap();
}

#[tokio::test]
async fn round_trip_functions_with_argument_signatures() {
    let driver = PgDriver::new();
    let conn = driver.open(&spec()).await.expect("open");
    let src = unique_schema("src_fn");
    let dst = unique_schema("dst_fn");

    exec_many(
        &driver,
        &conn,
        &[
            format!("CREATE SCHEMA \"{src}\""),
            format!("CREATE SCHEMA \"{dst}\""),
            format!(
                "CREATE FUNCTION \"{src}\".\"answer\"()
                 RETURNS integer
                 LANGUAGE sql
                 AS $$ SELECT 42 $$"
            ),
            format!(
                "CREATE FUNCTION \"{src}\".\"identity_int\"(x integer)
                 RETURNS integer
                 LANGUAGE sql
                 AS $$ SELECT x $$"
            ),
            format!(
                "CREATE FUNCTION \"{src}\".\"overloaded\"(x integer)
                 RETURNS text
                 LANGUAGE sql
                 AS $$ SELECT 'int:' || x::text $$"
            ),
            format!(
                "CREATE FUNCTION \"{src}\".\"overloaded\"(x text)
                 RETURNS text
                 LANGUAGE sql
                 AS $$ SELECT 'text:' || x $$"
            ),
        ],
    )
    .await;

    let shallow = driver
        .schema(
            conn.clone(),
            SchemaScope {
                depth: SchemaDepth::Shallow,
                filter: Some(SchemaFilter {
                    schemas: Some(vec![src.clone()]),
                    kinds: Some(vec![
                        ObjectKind::ScalarFunction,
                        ObjectKind::TableValuedFunction,
                    ]),
                    ..Default::default()
                }),
            },
        )
        .await
        .expect("shallow schema with routines");
    let routines: Vec<_> = shallow
        .trees
        .iter()
        .flat_map(|tree| &tree.schemas)
        .flat_map(|schema| &schema.objects)
        .map(|object| (object.name.as_str(), object.routine_args.clone()))
        .collect();
    assert!(
        routines.contains(&("answer", Some(Vec::new()))),
        "nullary routine args missing: {routines:?}"
    );
    assert!(
        routines.contains(&("identity_int", Some(vec!["integer".into()]))),
        "one-arg routine args missing: {routines:?}"
    );
    assert!(
        routines.contains(&("overloaded", Some(vec!["integer".into()])))
            && routines.contains(&("overloaded", Some(vec!["text".into()]))),
        "overload routine args missing: {routines:?}"
    );

    for (name, args) in [
        ("answer", Vec::new()),
        ("identity_int", vec!["integer".to_string()]),
        ("overloaded", vec!["integer".to_string()]),
        ("overloaded", vec!["text".to_string()]),
    ] {
        let path = ObjectPath {
            catalog: None,
            schema: Some(src.clone()),
            name: name.into(),
            kind: Some(ObjectKind::ScalarFunction),
            routine_args: Some(args),
        };
        let ddl = generate_ddl(&driver, conn.clone(), path)
            .await
            .unwrap_or_else(|error| panic!("generate function DDL for {name}: {error}"))
            .ddl;
        exec(&driver, &conn, retarget_schema(&ddl, &src, &dst)).await;
    }

    exec(
        &driver,
        &conn,
        format!(
            "SELECT \"{dst}\".\"answer\"(),
                    \"{dst}\".\"identity_int\"(41),
                    \"{dst}\".\"overloaded\"(1),
                    \"{dst}\".\"overloaded\"('x'::text)"
        ),
    )
    .await;

    driver.close(conn).await.unwrap();
}
