[package]
name = "sift-completion"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sift-protocol = { workspace = true }
sift-semantic = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
criterion = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sift-snippets = { workspace = true }

[[bench]]
name = "sql_editor_latency"
harness = false
