[package]
name = "sift-workspace-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gpui = { workspace = true }
sift-client-sdk = { workspace = true }
sift-ui = { workspace = true }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
